---
micronaut:
  application:
    name: learn-english-words
  server:
    port: 8080
    cors:
      enabled: true

---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:YOUD__DKJ&*@#1kljdkjlkdLKJDkd0kdkjkdjJJNLQPUYVM}"

#---
##datasources.default: {}
#---
#micronaut:
#  io:
#    watch:
#      paths: src/main
#      restart: true